# - name: Install/enable RPM fusion repository
#   dnf:
#     name: "https://mirrors.rpmfusion.org/free/el/{{item}}"
#     disable_gpg_check: yes
#     state: present
#   with_items:
#     - "rpmfusion-free-release-9.noarch.rpm"

# - name: Disable RPM fusion repository
#   dnf:
#     name: "rpmfusion-free-release"
#     state: absent

- name: Install passari-workflow
  pip:
    chdir: "{{passari_packages_dir}}"
    virtualenv: "{{passari_workflow_venv_dir}}"
    extra_args: "--find-links={{passari_packages_dir}}/wheels"
    requirements: "requirements-workflow.txt"
    virtualenv_command: "{{ passari_python_executable }} -m venv"
  become_user: "{{passari_user}}"
  tags: [passari-workflow-install, workflow-install, install]

# The bin directory needs to be set to bin_t type to allow the worker
# services to start
- name: Set SELinux context for venv bin directory
  sefcontext:
    target: "{{passari_workflow_venv_dir}}/bin(/.*)?"
    setype: bin_t
    state: present

- name: Apply SELinux context of venv bin directory
  command: "restorecon -Rv {{passari_workflow_venv_dir}}/bin"
  register: restorecon_result
  changed_when: "restorecon_result.stdout or restorecon_result.stderr"

- name: Add directory for SIP submission key
  file:
    path: "{{dpres_ssh_key_path | dirname}}"
    state: directory
    owner: "{{passari_user}}"
    group: "{{passari_user}}"
    mode: u=rwx,g=,o=

- name: Add SIP submission SSH key
  copy:
    content: "{{sip_submit_key}}"
    dest: "{{dpres_ssh_key_path}}"
    owner: "{{passari_user}}"
    group: "{{passari_user}}"
    mode: u=rw,g=,o=
  notify: Create or update .pub file for SIP submission SSH key
  when: sip_submit_key is defined and sip_submit_key

- name: Add SIP signing key
  copy:
    content: "{{sip_sign_key}}"
    dest: "{{sip_sign_key_path}}"
    owner: "{{passari_user}}"
    group: "{{passari_user}}"
    mode: u=rw,g=,o=
  notify: Create or update .pub file for SIP signing key
  when: sip_sign_key is defined and sip_sign_key

- name: Create passari configuration directories
  file:
    path: "{{item}}"
    state: directory
  loop:
    - "/etc/passari"
    - "/etc/passari-workflow"

- name: Create passari configuration file
  template:
    src: "templates/config/passari.config.toml.j2"
    dest: "/etc/passari/config.toml"
  tags: passari-workflow

- name: Create passari-workflow configuration file
  template:
    src: "templates/config/passari-workflow.config.toml.j2"
    dest: "/etc/passari-workflow/config.toml"

- name: Create workflow object and archive directories
  file:
    path: "{{item}}"
    state: directory
  become_user: "{{passari_user}}"
  loop:
    - "{{workflow_package_dir}}"
    - "{{workflow_archive_dir}}"

- name: Run database migrations
  command: "{{passari_workflow_venv_dir}}/bin/pas-db-migrate upgrade head"
  become_user: "{{passari_user}}"
  register: migrate_result
  changed_when: "'Running upgrade' in migrate_result.stderr"

- name: Create worker services
  template:
    src: "templates/config/passari-worker-NAME@.service.j2"
    dest: "/etc/systemd/system/passari-worker-{{item}}@.service"
  loop: "{{worker_names}}"
  notify: reload systemd

- name: Create worker stopper services
  template:
    src: "templates/config/passari-worker-stop-NAME@.service.j2"
    dest: "/etc/systemd/system/passari-worker-stop-{{item}}@.service"
  loop:
    - "download_object"
  notify: reload systemd

- name: Create worker timers
  template:
    src: "templates/config/passari-worker-{{item.prefix}}NAME@.timer.j2"
    dest: "/etc/systemd/system/passari-worker-{{item.prefix}}{{item.name}}@.timer"
  loop:
    - {prefix: "", name: "download_object"}
    - {prefix: "stop-", name: "download_object"}
  notify: reload systemd

- name: Create synchronization service files
  template:
    src: "templates/config/{{item}}.service.j2"
    dest: "/etc/systemd/system/{{item}}.service"
  loop:
    - "sync-attachments"
    - "sync-objects"
    - "sync-hashes"
    - "sync-processed-sips"
    - "stop-sync-attachments"
    - "stop-sync-objects"
  notify: reload systemd

- name: Create synchronization timer files
  template:
    src: "templates/config/{{item}}.timer.j2"
    dest: "/etc/systemd/system/{{item}}.timer"
  loop:
    - "sync-attachments"
    - "sync-objects"
    - "sync-hashes"
    - "sync-processed-sips"
    - "stop-sync-attachments"
    - "stop-sync-objects"
  notify: reload systemd

- name: Trigger handlers to reload systemd (if necessary)
  meta: flush_handlers

- name: Enable scheduled running of syncers
  systemd:
    name: "{{item.name}}.timer"
    state: "{% if item.enabled %}started{% else %}stopped{% endif %}"
    enabled: "{{item.enabled}}"
  loop:
    - {name: "sync-objects", enabled: "{{enable_sync_objects}}"}
    - {name: "stop-sync-objects", enabled: "{{enable_sync_objects}}"}
    - {name: "sync-attachments", enabled: "{{enable_sync_attachments}}"}
    - {name: "stop-sync-attachments", enabled: "{{enable_sync_attachments}}"}
    - {name: "sync-hashes", enabled: "{{enable_sync_hashes}}"}
    - {name: "sync-processed-sips", enabled: "{{enable_sync_processed_sips}}"}

- name: Test nested loop
  debug:
    msg: >-
      name: {{item.0}} |
      number: {{item.1}} |
      enabled: {{ item.1 <= worker_count[item.0] }}
  loop: "{{ worker_names | product(range(1, 8)) | list }}"
  tags: test

####################################################################
- name: Trigger handlers
  meta: flush_handlers
- name: Exit play here
  meta: end_play
########################################################### END END


- name: Stop workers
  command: "systemctl stop passari-worker-{{item}}@*"
  loop: "{{worker_names}}"

- name: Disable workers
  command: "systemctl disable passari-worker-{{item}}@*"
  loop: "{{worker_names}}"

- name: Enable and start download-object workers
  systemd:
    name: "passari-worker-download_object@{{item}}.service"
    state: restarted
    enabled: true
  loop: "{{ range(0, worker_count['download_object']) | list }}"
  when: not enable_scheduled_download_objects

# It's necessary to disable the service itself if a deployment moves
# from having the service enabled to having it enabled on certain times
- name: Disable download-object worker
  systemd:
    name: "passari-worker-download_object@{{item}}.service"
    enabled: false
  loop: "{{ range(0, worker_count['download_object']) | list }}"
  when: enable_scheduled_download_objects

- name: Enable download-object timer
  systemd:
    name: "passari-worker-download_object@{{item}}.timer"
    state: "{% if enable_scheduled_download_objects %}started{% else %}stopped{% endif %}"
    enabled: "{{enable_scheduled_download_objects}}"
  loop: "{{ range(0, worker_count['download_object']) | list }}"

- name: Enable stop-download-object timer
  systemd:
    name: "passari-worker-stop-download_object@{{item}}.timer"
    state: "{% if enable_scheduled_download_objects %}started{% else %}stopped{% endif %}"
    enabled: "{{enable_scheduled_download_objects}}"
  loop: "{{ range(0, worker_count['download_object']) | list }}"

- name: Enable and start create-sip workers
  systemd:
    name: "create-sip-worker@{{item}}"
    state: restarted
    enabled: true
  loop: "{{ range(0, worker_count['create_sip']) | list }}"

- name: Enable and start submit-sip workers
  systemd:
    name: "submit-sip-worker@{{item}}"
    state: restarted
    enabled: true
  loop: "{{ range(0, worker_count['submit_sip']) | list }}"

- name: Enable and start confirm-sip workers
  systemd:
    name: "confirm-sip-worker@{{item}}"
    state: restarted
    enabled: true
  loop: "{{ range(0, worker_count['confirm_sip']) | list }}"
