---
# Passari variables
#
# To deploy Passari to a new environment, it is recommended to make
# a new encrypted copy of this file and make changes to the variables as
# necessary, *especially* for credentials that should be replaced with
# randomly generated secure values.
#
# Commented variables in the new file will use the defaults defined in
# group_vars/all. Once a copy of this file is created, it is recommended
# to comment out any variables that have not been changed from the defaults.


####
#### Workflow - filesystem
####

passari_workflow_install_path: "{{passari_home}}/passari-workflow"
passari_web_ui_install_path: "{{passari_home}}/passari-web-ui"

siptools_user: "passari"
siptools_install_path: "/home/passari/dpres-siptools"


####
#### Database
####
# PostgreSQL database name
db_name: passari

####
#### Web UI
####
# Domain used when serving the web UI. Replace this if a proper domain
# is available.
site_domain: localhost


####
#### Web UI - SSL certificate
####
# Whether to generate a Let's Encrypt certificate. A proper domain
# is required for this.
enable_letsencrypt: false

# Used for Let's Encrypt
#letsencrypt_admin_email: ""
