version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy
    volumes:
      - .:/app
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      DATABASE_URL: postgresql://passari:passari@db/passari
      REDIS_URL: redis://redis:6379/0
    env_file:
      - .env.defaults
      - .env

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: passari
      POSTGRES_PASSWORD: passari
      POSTGRES_DB: passari
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U passari"
      interval: 1s
      retries: 15

  redis:
    image: redis:7
    volumes:
      - redis_data:/data

  # Redis Commander (Web Interface for Redis)
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      REDIS_HOSTS: "local:redis:6379"
    ports:
      - "127.0.0.1:8081:8081"

volumes:
  postgres_data:
  redis_data:
