- name: Update all packages
  yum:
    name: "*"
    state: latest
  tags: [common-update, update]

- name: Install important packages
  dnf:
    name:
      - etckeeper
      - sudo
      - python3-policycoreutils  # Required for sefcontext
  tags: [common-packages, common-install, install, sudo, etckeeper]

- name: Initialize etckeeper
  command: etckeeper init
  args:
    chdir: /etc
    creates: /etc/.etckeeper
  notify: Commit initial etc changes
  tags: etckeeper

- name: Flush handlers to commit etckeeper changes
  meta: flush_handlers
  tags: etckeeper

- name: Enable EPEL software repository
  dnf:
    name: epel-release

- name: Create /var/log/journal to enable persistent logging
  file:
    path: "/var/log/journal"
    state: directory
  notify: restart systemd-journald
