- name: restart systemd-journald
  systemd_service:
    name: systemd-journald
    state: restarted
  # 'systemd-journald' does not exist inside Docker containers
  ignore_errors: true

- name: Commit initial etc changes
  command: "etckeeper commit Init"
  args:
    chdir: /etc
