[db]
# PostgreSQL server credentials can be specified here, but if not, they
# are taken from PASSARI_WORKFLOW_DB_URL or DATABASE_URL env variable.
#url='$PASSARI_WORKFLOW_DB_URL'

[redis]
# Redis server credentials can be specified here, but if not, they are
# taken from PASSARI_WORKFLOW_REDIS_URL or REDIS_URL env variable. The
# latter is also used by RQ by default.
#url='$PASSARI_WORKFLOW_REDIS_URL'

[package]
# Directory used for packages under processing.
# It is recommended to use a high performance and high capacity storage
# for this directory, as the workflow cannot know the size of individual
# files before downloading them.
# This should *not* be located in the same filesystem as the Redis and
# PostgreSQL, as the filesystem can otherwise get full at random due to the
# aforementioned reason.
package_dir='$PASSARI_WORKFLOW_PACKAGE_DIR'

# Directory used for storing preservation reports for each processed SIP.
# These files are not read automatically by the workflow and are accessible
# only through the web UI, meaning it is recommended to use a storage
# designed for infrequent reads.
archive_dir='$PASSARI_WORKFLOW_ARCHIVE_DIR'

# Delay before a new package will enter preservation.
# Default is 30 days (2592000 seconds)
preservation_delay=2592000

# Delay before a preserved package will be updated if changed.
# Default is 30 days (2592000 seconds)
update_delay=2592000
